name: Gitleaks
description: Run Gitleaks on Push and PR events
branding:
  color: purple
  icon: eye
runs:
  using: "docker"
  image: "Dockerfile"
inputs:
  gitleaksConfig:
    description: 'path to gitleaks config from root directory'
    required: false
    default: ''
